# Uses Nerd Font: Hack Nerd Font Mono

format = """
[░▒▓](#a3aed2)\
$hostname\
$os\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](bg:#477fed fg:#769ff0)\
$aws\
[](fg:#477fed bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$golang\
$java\
$nodejs\
$rust\
$php\
$python\
$ruby\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[aws]
format = "[ $symbol $region ]($style)"
style = "fg:#e3e5e5 bg:#477fed"
symbol = "󰸏"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = ""
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[hostname]
ssh_only = false
ssh_symbol = ""
style = "bg:#a3aed2 fg:#090c0c"
trim_at = '.amazon.com'
format = "[ $ssh_symbol]($style)"

[os]
disabled = false
style = "bg:#a3aed2 fg:#090c0c"
format = "[ $symbol ]($style)"

[os.symbols]
Amazon = ""
Linux = ""
Macos = ""

[golang]
symbol = "ﳑ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[java]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[ruby]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%T" # Hour:Minute:Second Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
